

(define CHARACTERS (string->list "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_"))
(define NUMBERS-0-TO-9 (string->list "0123456789"))
(define NUMBERS-1-TO-9 (string->list "123456789"))
(define WHITESPACE (string->list "\n\r\t "))

(define STATE_NONE "0")
(define STATE_START "1")
(define STATE_A "2")
(define STATE_AB "3")
(define STATE_ABS "4")
(define STATE_ABST "5")
(define STATE_ABSTR "6")
(define STATE_ABSTRA "7")
(define STATE_ABSTRAC "8")
(define STATE_ABSTRACT "9")
(define STATE_B "10")
(define STATE_BO "11")
(define STATE_BOO "12")
(define STATE_BOOL "13")
(define STATE_BOOLE "14")
(define STATE_BOOLEA "15")
(define STATE_BOOLEAN "16")
(define STATE_BY "17")
(define STATE_BYT "18")
(define STATE_BYTE "19")
(define STATE_C "20")
(define STATE_CH "21")
(define STATE_CHA "22")
(define STATE_CHAR "23")
(define STATE_CL "24")
(define STATE_CLA "25")
(define STATE_CLAS "26")
(define STATE_CLASS "27")
(define STATE_E "28")
(define STATE_EX "29")
(define STATE_EXT "30")
(define STATE_EXTE "31")
(define STATE_EXTEN "32")
(define STATE_EXTEND "33")
(define STATE_EXTENDS "34")
(define STATE_F "35")
(define STATE_FA "36")
(define STATE_FAL "37")
(define STATE_FALS "38")
(define STATE_FALSE "39")
(define STATE_FI "40")
(define STATE_FIN "41")
(define STATE_FINA "42")
(define STATE_FINAL "43")
(define STATE_FO "44")
(define STATE_FOR "45")
(define STATE_I "46")
(define STATE_IF "47")
(define STATE_IM "48")
(define STATE_IMP "49")
(define STATE_IMPL "50")
(define STATE_IMPLE "51")
(define STATE_IMPLEM "52")
(define STATE_IMPLEME "53")
(define STATE_IMPLEMEN "54")
(define STATE_IMPLEMENT "55")
(define STATE_IMPLEMENTS "56")
(define STATE_IMPO "57")
(define STATE_IMPOR "58")
(define STATE_IMPORT "59")
(define STATE_IN "60")
(define STATE_INS "61")
(define STATE_INST "62")
(define STATE_INSTA "63")
(define STATE_INSTAN "64")
(define STATE_INSTANC "65")
(define STATE_INSTANCE "66")
(define STATE_INSTANCEO "67")
(define STATE_INSTANCEOF "68")
(define STATE_INT "69")
(define STATE_INTE "70")
(define STATE_INTER "71")
(define STATE_INTERF "72")
(define STATE_INTERFA "73")
(define STATE_INTERFAC "74")
(define STATE_INTERFACE "75")
(define STATE_N "76")
(define STATE_NA "77")
(define STATE_NAT "78")
(define STATE_NATI "79")
(define STATE_NATIV "80")
(define STATE_NATIVE "81")
(define STATE_NU "82")
(define STATE_NUL "83")
(define STATE_NULL "84")
(define STATE_P "85")
(define STATE_PA "86")
(define STATE_PAC "87")
(define STATE_PACK "88")
(define STATE_PACKA "89")
(define STATE_PACKAG "90")
(define STATE_PACKAGE "91")
(define STATE_PR "92")
(define STATE_PRO "93")
(define STATE_PROT "94")
(define STATE_PROTE "95")
(define STATE_PROTEC "96")
(define STATE_PROTECT "97")
(define STATE_PROTECTE "98")
(define STATE_PROTECTED "99")
(define STATE_PU "100")
(define STATE_PUB "101")
(define STATE_PUBL "102")
(define STATE_PUBLI "103")
(define STATE_PUBLIC "104")
(define STATE_R "105")
(define STATE_RE "106")
(define STATE_RET "107")
(define STATE_RETU "108")
(define STATE_RETUR "109")
(define STATE_RETURN "110")
(define STATE_S "111")
(define STATE_SH "112")
(define STATE_SHO "113")
(define STATE_SHOR "114")
(define STATE_SHORT "115")
(define STATE_ST "116")
(define STATE_STA "117")
(define STATE_STAT "118")
(define STATE_STATI "119")
(define STATE_STATIC "120")
(define STATE_T "121")
(define STATE_TR "122")
(define STATE_TRU "123")
(define STATE_TRUE "124")
(define STATE_V "125")
(define STATE_VO "126")
(define STATE_VOI "127")
(define STATE_VOID "128")
(define STATE_W "129")
(define STATE_WH "130")
(define STATE_WHI "131")
(define STATE_WHIL "132")
(define STATE_WHILE "133")
(define STATE_ID "134")
(define STATE_LBRACKET "135")
(define STATE_RBRACKET "136")
(define STATE_LPAREN "137")
(define STATE_RPAREN "138")
(define STATE_LBRACE "139")
(define STATE_RBRACE "140")
(define STATE_QUOT "141")
(define STATE_S_QUOT "142")
(define STATE_PLUS "143")
(define STATE_MINUS "144")
(define STATE_STAR "145")
(define STATE_DIVIDE "146")
(define STATE_COMMENT "147")
(define STATE_MOD "148")
(define STATE_ASSIGN "149")
(define STATE_NOT "150")
(define STATE_GT "151")
(define STATE_LT "152")
(define STATE_GE "153")
(define STATE_LE "154")
(define STATE_NE "155")
(define STATE_EQ "156")
(define STATE_OR "157")
(define STATE_AND "158")
(define STATE_OR_OR "159")
(define STATE_AND_AND "160")
(define STATE_SEMI_COLON "161")
(define STATE_DOT "162")
(define STATE_COMMA "163")
(define STATE_WHITESPACE "164")
(define STATE_NUM "165")
(define STATE_ERROR "166")
(define STATE_TH "167")
(define STATE_THI "168")
(define STATE_THIS "169")

(define state-transitions (make-hash))
(define state-types (make-hash))

(define (get-key x y) 
  (string-append x (make-string 1 y)))

(define (set-transition from transitions to)
  (for-each (lambda (transition) (hash-set! state-transitions (get-key from transition) to)) transitions))
;  (cond
;    [(empty? transitions) void]
;    [else (hash-set! state-transitions (get-key from (first transitions)) to)
;          (set-transition from (rest transitions) to)]))

(define (set-state-type state type)
  (hash-set! state-types state type))

;(define (set-transition from transitions to)
;  (map (lambda (x) (hash-set! state-transitions (get-key from x) to) ) transitions))

(define (get-transition from transition)
  (hash-ref state-transitions (get-key from transition) "0"))

(define (get-state-type state)
  (hash-ref state-types state "NONE"))

(set-transition STATE_START WHITESPACE STATE_WHITESPACE)
(set-transition STATE_WHITESPACE WHITESPACE STATE_WHITESPACE)
(set-transition STATE_START CHARACTERS STATE_ID)
(set-transition STATE_ID (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START NUMBERS-0-TO-9 STATE_NUM)
(set-transition STATE_NUM NUMBERS-0-TO-9 STATE_NUM)
(set-transition STATE_NUM CHARACTERS STATE_ERROR)
(set-transition STATE_ERROR (append CHARACTERS NUMBERS-0-TO-9) STATE_ERROR)
(set-transition STATE_START '(#\[) STATE_LBRACKET)
(set-transition STATE_START '(#\]) STATE_RBRACKET)
(set-transition STATE_START '(#\() STATE_LPAREN)
(set-transition STATE_START '(#\)) STATE_RPAREN)
(set-transition STATE_START '(#\{) STATE_LBRACE)
(set-transition STATE_START '(#\}) STATE_RBRACE)
(set-transition STATE_START '(#\") STATE_QUOT)
(set-transition STATE_START '(#\') STATE_S_QUOT)
(set-transition STATE_START '(#\+) STATE_PLUS)
(set-transition STATE_START '(#\-) STATE_MINUS)
(set-transition STATE_START '(#\*) STATE_STAR)
(set-transition STATE_START '(#\/) STATE_DIVIDE)
(set-transition STATE_DIVIDE '(#\/) STATE_COMMENT)
(set-transition STATE_START '(#\%) STATE_MOD)
(set-transition STATE_START '(#\=) STATE_ASSIGN)
(set-transition STATE_START '(#\!) STATE_NOT)
(set-transition STATE_START '(#\>) STATE_GT)
(set-transition STATE_START '(#\<) STATE_LT)
(set-transition STATE_GT '(#\=) STATE_GE)
(set-transition STATE_LT '(#\=) STATE_LE)
(set-transition STATE_NOT '(#\=) STATE_NE)
(set-transition STATE_ASSIGN '(#\=) STATE_EQ)
(set-transition STATE_START '(#\|) STATE_OR)
(set-transition STATE_START '(#\&) STATE_AND)
(set-transition STATE_OR '(#\|) STATE_OR_OR)
(set-transition STATE_AND '(#\&) STATE_AND_AND)
(set-transition STATE_START '(#\;) STATE_SEMI_COLON)
(set-transition STATE_START '(#\.) STATE_DOT)
(set-transition STATE_START '(#\,) STATE_COMMA)
(set-transition STATE_START '(#\a) STATE_A)
(set-transition STATE_A (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_A '(#\b) STATE_AB)
(set-transition STATE_AB (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_AB '(#\s) STATE_ABS)
(set-transition STATE_ABS (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_ABS '(#\t) STATE_ABST)
(set-transition STATE_ABST (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_ABST '(#\r) STATE_ABSTR)
(set-transition STATE_ABSTR (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_ABSTR '(#\a) STATE_ABSTRA)
(set-transition STATE_ABSTRA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_ABSTRA '(#\c) STATE_ABSTRAC)
(set-transition STATE_ABSTRAC (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_ABSTRAC '(#\t) STATE_ABSTRACT)
(set-transition STATE_ABSTRACT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\b) STATE_B)
(set-transition STATE_B (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_B '(#\o) STATE_BO)
(set-transition STATE_BO (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_BO '(#\o) STATE_BOO)
(set-transition STATE_BOO (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_BOO '(#\l) STATE_BOOL)
(set-transition STATE_BOOL (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_BOOL '(#\e) STATE_BOOLE)
(set-transition STATE_BOOLE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_BOOLE '(#\a) STATE_BOOLEA)
(set-transition STATE_BOOLEA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_BOOLEA '(#\n) STATE_BOOLEAN)
(set-transition STATE_BOOLEAN (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_B '(#\y) STATE_BY)
(set-transition STATE_BY (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_BY '(#\t) STATE_BYT)
(set-transition STATE_BYT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_BYT '(#\e) STATE_BYTE)
(set-transition STATE_BYTE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\c) STATE_C)
(set-transition STATE_C (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_C '(#\h) STATE_CH)
(set-transition STATE_CH (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_CH '(#\a) STATE_CHA)
(set-transition STATE_CHA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_CHA '(#\r) STATE_CHAR)
(set-transition STATE_CHAR (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_C '(#\l) STATE_CL)
(set-transition STATE_CL (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_CL '(#\a) STATE_CLA)
(set-transition STATE_CLA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_CLA '(#\s) STATE_CLAS)
(set-transition STATE_CLAS (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_CLAS '(#\s) STATE_CLASS)
(set-transition STATE_CLASS (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\e) STATE_E)
(set-transition STATE_E (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_E '(#\x) STATE_EX)
(set-transition STATE_EX (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_EX '(#\t) STATE_EXT)
(set-transition STATE_EXT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_EXT '(#\e) STATE_EXTE)
(set-transition STATE_EXTE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_EXTE '(#\n) STATE_EXTEN)
(set-transition STATE_EXTEN (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_EXTEN '(#\d) STATE_EXTEND)
(set-transition STATE_EXTEND (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_EXTEND '(#\s) STATE_EXTENDS)
(set-transition STATE_EXTENDS (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\f) STATE_F)
(set-transition STATE_F (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_F '(#\a) STATE_FA)
(set-transition STATE_FA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_FA '(#\l) STATE_FAL)
(set-transition STATE_FAL (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_FAL '(#\s) STATE_FALS)
(set-transition STATE_FALS (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_FALS '(#\e) STATE_FALSE)
(set-transition STATE_FALSE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_F '(#\i) STATE_FI)
(set-transition STATE_FI (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_FI '(#\n) STATE_FIN)
(set-transition STATE_FIN (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_FIN '(#\a) STATE_FINA)
(set-transition STATE_FINA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_FINA '(#\l) STATE_FINAL)
(set-transition STATE_FINAL (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_F '(#\o) STATE_FO)
(set-transition STATE_FO (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_FO '(#\r) STATE_FOR)
(set-transition STATE_FOR (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\i) STATE_I)
(set-transition STATE_I (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_I '(#\f) STATE_IF)
(set-transition STATE_IF (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_I '(#\m) STATE_IM)
(set-transition STATE_IM (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IM '(#\p) STATE_IMP)
(set-transition STATE_IMP (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMP '(#\l) STATE_IMPL)
(set-transition STATE_IMPL (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMPL '(#\e) STATE_IMPLE)
(set-transition STATE_IMPLE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMPLE '(#\m) STATE_IMPLEM)
(set-transition STATE_IMPLEM (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMPLEM '(#\e) STATE_IMPLEME)
(set-transition STATE_IMPLEME (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMPLEME '(#\n) STATE_IMPLEMEN)
(set-transition STATE_IMPLEMEN (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMPLEMEN '(#\t) STATE_IMPLEMENT)
(set-transition STATE_IMPLEMENT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMPLEMENT '(#\s) STATE_IMPLEMENTS)
(set-transition STATE_IMPLEMENTS (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMP '(#\o) STATE_IMPO)
(set-transition STATE_IMPO (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMPO '(#\r) STATE_IMPOR)
(set-transition STATE_IMPOR (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IMPOR '(#\t) STATE_IMPORT)
(set-transition STATE_IMPORT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_I '(#\n) STATE_IN)
(set-transition STATE_IN (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IN '(#\s) STATE_INS)
(set-transition STATE_INS (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INS '(#\t) STATE_INST)
(set-transition STATE_INST (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INST '(#\a) STATE_INSTA)
(set-transition STATE_INSTA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INSTA '(#\n) STATE_INSTAN)
(set-transition STATE_INSTAN (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INSTAN '(#\c) STATE_INSTANC)
(set-transition STATE_INSTANC (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INSTANC '(#\e) STATE_INSTANCE)
(set-transition STATE_INSTANCE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INSTANCE '(#\o) STATE_INSTANCEO)
(set-transition STATE_INSTANCEO (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INSTANCEO '(#\f) STATE_INSTANCEOF)
(set-transition STATE_INSTANCEOF (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_IN '(#\t) STATE_INT)
(set-transition STATE_INT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INT '(#\e) STATE_INTE)
(set-transition STATE_INTE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INTE '(#\r) STATE_INTER)
(set-transition STATE_INTER (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INTER '(#\f) STATE_INTERF)
(set-transition STATE_INTERF (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INTERF '(#\a) STATE_INTERFA)
(set-transition STATE_INTERFA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INTERFA '(#\c) STATE_INTERFAC)
(set-transition STATE_INTERFAC (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_INTERFAC '(#\e) STATE_INTERFACE)
(set-transition STATE_INTERFACE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\n) STATE_N)
(set-transition STATE_N (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_N '(#\a) STATE_NA)
(set-transition STATE_NA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_NA '(#\t) STATE_NAT)
(set-transition STATE_NAT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_NAT '(#\i) STATE_NATI)
(set-transition STATE_NATI (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_NATI '(#\v) STATE_NATIV)
(set-transition STATE_NATIV (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_NATIV '(#\e) STATE_NATIVE)
(set-transition STATE_NATIVE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_N '(#\u) STATE_NU)
(set-transition STATE_NU (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_NU '(#\l) STATE_NUL)
(set-transition STATE_NUL (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_NUL '(#\l) STATE_NULL)
(set-transition STATE_NULL (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\p) STATE_P)
(set-transition STATE_P (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_P '(#\a) STATE_PA)
(set-transition STATE_PA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PA '(#\c) STATE_PAC)
(set-transition STATE_PAC (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PAC '(#\k) STATE_PACK)
(set-transition STATE_PACK (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PACK '(#\a) STATE_PACKA)
(set-transition STATE_PACKA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PACKA '(#\g) STATE_PACKAG)
(set-transition STATE_PACKAG (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PACKAG '(#\e) STATE_PACKAGE)
(set-transition STATE_PACKAGE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_P '(#\r) STATE_PR)
(set-transition STATE_PR (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PR '(#\o) STATE_PRO)
(set-transition STATE_PRO (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PRO '(#\t) STATE_PROT)
(set-transition STATE_PROT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PROT '(#\e) STATE_PROTE)
(set-transition STATE_PROTE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PROTE '(#\c) STATE_PROTEC)
(set-transition STATE_PROTEC (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PROTEC '(#\t) STATE_PROTECT)
(set-transition STATE_PROTECT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PROTECT '(#\e) STATE_PROTECTE)
(set-transition STATE_PROTECTE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PROTECTE '(#\d) STATE_PROTECTED)
(set-transition STATE_PROTECTED (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_P '(#\u) STATE_PU)
(set-transition STATE_PU (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PU '(#\b) STATE_PUB)
(set-transition STATE_PUB (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PUB '(#\l) STATE_PUBL)
(set-transition STATE_PUBL (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PUBL '(#\i) STATE_PUBLI)
(set-transition STATE_PUBLI (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_PUBLI '(#\c) STATE_PUBLIC)
(set-transition STATE_PUBLIC (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\r) STATE_R)
(set-transition STATE_R (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_R '(#\e) STATE_RE)
(set-transition STATE_RE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_RE '(#\t) STATE_RET)
(set-transition STATE_RET (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_RET '(#\u) STATE_RETU)
(set-transition STATE_RETU (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_RETU '(#\r) STATE_RETUR)
(set-transition STATE_RETUR (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_RETUR '(#\n) STATE_RETURN)
(set-transition STATE_RETURN (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\s) STATE_S)
(set-transition STATE_S (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_S '(#\h) STATE_SH)
(set-transition STATE_SH (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_SH '(#\o) STATE_SHO)
(set-transition STATE_SHO (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_SHO '(#\r) STATE_SHOR)
(set-transition STATE_SHOR (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_SHOR '(#\t) STATE_SHORT)
(set-transition STATE_SHORT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_S '(#\t) STATE_ST)
(set-transition STATE_ST (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_ST '(#\a) STATE_STA)
(set-transition STATE_STA (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_STA '(#\t) STATE_STAT)
(set-transition STATE_STAT (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_STAT '(#\i) STATE_STATI)
(set-transition STATE_STATI (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_STATI '(#\c) STATE_STATIC)
(set-transition STATE_STATIC (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\t) STATE_T)
(set-transition STATE_T (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_T '(#\r) STATE_TR)
(set-transition STATE_TR (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_TR '(#\u) STATE_TRU)
(set-transition STATE_TRU (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_TRU '(#\e) STATE_TRUE)
(set-transition STATE_TRUE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_T '(#\h) STATE_TH)
(set-transition STATE_TH (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_TH '(#\i) STATE_THI)
(set-transition STATE_THI (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_THI '(#\s) STATE_THIS)
(set-transition STATE_THIS (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\v) STATE_V)
(set-transition STATE_V (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_V '(#\o) STATE_VO)
(set-transition STATE_VO (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_VO '(#\i) STATE_VOI)
(set-transition STATE_VOI (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_VOI '(#\d) STATE_VOID)
(set-transition STATE_VOID (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_START '(#\w) STATE_W)
(set-transition STATE_W (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_W '(#\h) STATE_WH)
(set-transition STATE_WH (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_WH '(#\i) STATE_WHI)
(set-transition STATE_WHI (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_WHI '(#\l) STATE_WHIL)
(set-transition STATE_WHIL (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)
(set-transition STATE_WHIL '(#\e) STATE_WHILE)
(set-transition STATE_WHILE (append CHARACTERS NUMBERS-0-TO-9) STATE_ID)

(require racket/include)
(include "tokens.rkt")

(set-state-type STATE_A TOKEN_ID)
(set-state-type STATE_AB TOKEN_ID)
(set-state-type STATE_ABS TOKEN_ID)
(set-state-type STATE_ABST TOKEN_ID)
(set-state-type STATE_ABSTR TOKEN_ID)
(set-state-type STATE_ABSTRA TOKEN_ID)
(set-state-type STATE_ABSTRAC TOKEN_ID)
(set-state-type STATE_ABSTRACT TOKEN_ABSTRACT)
(set-state-type STATE_B TOKEN_ID)
(set-state-type STATE_BO TOKEN_ID)
(set-state-type STATE_BOO TOKEN_ID)
(set-state-type STATE_BOOL TOKEN_ID)
(set-state-type STATE_BOOLE TOKEN_ID)
(set-state-type STATE_BOOLEA TOKEN_ID)
(set-state-type STATE_BOOLEAN TOKEN_BOOLEAN)
(set-state-type STATE_BY TOKEN_ID)
(set-state-type STATE_BYT TOKEN_ID)
(set-state-type STATE_BYTE TOKEN_BYTE)
(set-state-type STATE_C TOKEN_ID)
(set-state-type STATE_CH TOKEN_ID)
(set-state-type STATE_CHA TOKEN_ID)
(set-state-type STATE_CHAR TOKEN_CHAR)
(set-state-type STATE_CL TOKEN_ID)
(set-state-type STATE_CLA TOKEN_ID)
(set-state-type STATE_CLAS TOKEN_ID)
(set-state-type STATE_CLASS TOKEN_CLASS)
(set-state-type STATE_E TOKEN_ID)
(set-state-type STATE_EX TOKEN_ID)
(set-state-type STATE_EXT TOKEN_ID)
(set-state-type STATE_EXTE TOKEN_ID)
(set-state-type STATE_EXTEN TOKEN_ID)
(set-state-type STATE_EXTEND TOKEN_ID)
(set-state-type STATE_EXTENDS TOKEN_EXTENDS)
(set-state-type STATE_F TOKEN_ID)
(set-state-type STATE_FA TOKEN_ID)
(set-state-type STATE_FAL TOKEN_ID)
(set-state-type STATE_FALS TOKEN_ID)
(set-state-type STATE_FALSE TOKEN_FALSE)
(set-state-type STATE_FI TOKEN_ID)
(set-state-type STATE_FIN TOKEN_ID)
(set-state-type STATE_FINA TOKEN_ID)
(set-state-type STATE_FINAL TOKEN_FINAL)
(set-state-type STATE_FO TOKEN_ID)
(set-state-type STATE_FOR TOKEN_FOR)
(set-state-type STATE_I TOKEN_ID)
(set-state-type STATE_IF TOKEN_IF)
(set-state-type STATE_IM TOKEN_ID)
(set-state-type STATE_IMP TOKEN_ID)
(set-state-type STATE_IMPL TOKEN_ID)
(set-state-type STATE_IMPLE TOKEN_ID)
(set-state-type STATE_IMPLEM TOKEN_ID)
(set-state-type STATE_IMPLEME TOKEN_ID)
(set-state-type STATE_IMPLEMEN TOKEN_ID)
(set-state-type STATE_IMPLEMENT TOKEN_ID)
(set-state-type STATE_IMPLEMENTS TOKEN_IMPLEMENTS)
(set-state-type STATE_IMPO TOKEN_ID)
(set-state-type STATE_IMPOR TOKEN_ID)
(set-state-type STATE_IMPORT TOKEN_IMPORT)
(set-state-type STATE_IN TOKEN_ID)
(set-state-type STATE_INT TOKEN_INT)
(set-state-type STATE_INTE TOKEN_ID)
(set-state-type STATE_INTER TOKEN_ID)
(set-state-type STATE_INTERF TOKEN_ID)
(set-state-type STATE_INTERFA TOKEN_ID)
(set-state-type STATE_INTERFAC TOKEN_ID)
(set-state-type STATE_INTERFACE TOKEN_INTERFACE)
(set-state-type STATE_INS TOKEN_ID)
(set-state-type STATE_INST TOKEN_ID)
(set-state-type STATE_INSTA TOKEN_ID)
(set-state-type STATE_INSTAN TOKEN_ID)
(set-state-type STATE_INSTANC TOKEN_ID)
(set-state-type STATE_INSTANCE TOKEN_ID)
(set-state-type STATE_INSTANCEO TOKEN_ID)
(set-state-type STATE_INSTANCEOF TOKEN_INSTANCEOF)
(set-state-type STATE_N TOKEN_ID)
(set-state-type STATE_NA TOKEN_ID)
(set-state-type STATE_NAT TOKEN_ID)
(set-state-type STATE_NATI TOKEN_ID)
(set-state-type STATE_NATIV TOKEN_ID)
(set-state-type STATE_NATIVE TOKEN_NATIVE)
(set-state-type STATE_NU TOKEN_ID)
(set-state-type STATE_NUL TOKEN_ID)
(set-state-type STATE_NULL TOKEN_NULL)
(set-state-type STATE_P TOKEN_ID)
(set-state-type STATE_PA TOKEN_ID)
(set-state-type STATE_PAC TOKEN_ID)
(set-state-type STATE_PACK TOKEN_ID)
(set-state-type STATE_PACKA TOKEN_ID)
(set-state-type STATE_PACKAG TOKEN_ID)
(set-state-type STATE_PACKAGE TOKEN_PACKAGE)
(set-state-type STATE_PU TOKEN_ID)
(set-state-type STATE_PUB TOKEN_ID)
(set-state-type STATE_PUBL TOKEN_ID)
(set-state-type STATE_PUBLI TOKEN_ID)
(set-state-type STATE_PUBLIC TOKEN_PUBLIC)
(set-state-type STATE_PR TOKEN_ID)
(set-state-type STATE_PRO TOKEN_ID)
(set-state-type STATE_PROT TOKEN_ID)
(set-state-type STATE_PROTE TOKEN_ID)
(set-state-type STATE_PROTEC TOKEN_ID)
(set-state-type STATE_PROTECT TOKEN_ID)
(set-state-type STATE_PROTECTE TOKEN_ID)
(set-state-type STATE_PROTECTED TOKEN_PROTECTED)
(set-state-type STATE_R TOKEN_ID)
(set-state-type STATE_RE TOKEN_ID)
(set-state-type STATE_RET TOKEN_ID)
(set-state-type STATE_RETU TOKEN_ID)
(set-state-type STATE_RETUR TOKEN_ID)
(set-state-type STATE_RETURN TOKEN_RETURN)
(set-state-type STATE_S TOKEN_ID)
(set-state-type STATE_SH TOKEN_ID)
(set-state-type STATE_SHO TOKEN_ID)
(set-state-type STATE_SHOR TOKEN_ID)
(set-state-type STATE_SHORT TOKEN_SHORT)
(set-state-type STATE_ST TOKEN_ID)
(set-state-type STATE_STA TOKEN_ID)
(set-state-type STATE_STAT TOKEN_ID)
(set-state-type STATE_STATI TOKEN_ID)
(set-state-type STATE_STATIC TOKEN_STATIC)
(set-state-type STATE_T TOKEN_ID)
(set-state-type STATE_TH TOKEN_ID)
(set-state-type STATE_THI TOKEN_ID)
(set-state-type STATE_THIS TOKEN_THIS)
(set-state-type STATE_TR TOKEN_ID)
(set-state-type STATE_TRU TOKEN_ID)
(set-state-type STATE_TRUE TOKEN_TRUE)
(set-state-type STATE_V TOKEN_ID)
(set-state-type STATE_VO TOKEN_ID)
(set-state-type STATE_VOI TOKEN_ID)
(set-state-type STATE_VOID TOKEN_VOID)
(set-state-type STATE_W TOKEN_ID)
(set-state-type STATE_WH TOKEN_ID)
(set-state-type STATE_WHI TOKEN_ID)
(set-state-type STATE_WHIL TOKEN_ID)
(set-state-type STATE_WHILE TOKEN_WHILE)
(set-state-type STATE_NONE TOKEN_NONE)
(set-state-type STATE_ERROR TOKEN_NONE)
(set-state-type STATE_START TOKEN_WHITESPACE)
(set-state-type STATE_WHITESPACE TOKEN_WHITESPACE)
(set-state-type STATE_LBRACKET TOKEN_LBRACKET)
(set-state-type STATE_RBRACKET TOKEN_RBRACKET)
(set-state-type STATE_LPAREN TOKEN_LPAREN)
(set-state-type STATE_RPAREN TOKEN_RPAREN)
(set-state-type STATE_LBRACE TOKEN_LBRACE)
(set-state-type STATE_RBRACE TOKEN_RBRACE)
(set-state-type STATE_QUOT TOKEN_QUOT)
(set-state-type STATE_S_QUOT TOKEN_S_QUOT)
(set-state-type STATE_PLUS TOKEN_PLUS)
(set-state-type STATE_MINUS TOKEN_MINUS)
(set-state-type STATE_STAR TOKEN_STAR)
(set-state-type STATE_DIVIDE TOKEN_DIVIDE)
(set-state-type STATE_COMMENT TOKEN_COMMENT)
(set-state-type STATE_MOD TOKEN_MOD)
(set-state-type STATE_ASSIGN TOKEN_ASSIGN)
(set-state-type STATE_NOT TOKEN_NOT)
(set-state-type STATE_GT TOKEN_GT)
(set-state-type STATE_LT TOKEN_LT)
(set-state-type STATE_GE TOKEN_GE)
(set-state-type STATE_LE TOKEN_LE)
(set-state-type STATE_NE TOKEN_NE)
(set-state-type STATE_EQ TOKEN_EQ)
(set-state-type STATE_OR TOKEN_OR)
(set-state-type STATE_AND TOKEN_AND)
(set-state-type STATE_OR_OR TOKEN_OR_OR)
(set-state-type STATE_AND_AND TOKEN_AND_AND)
(set-state-type STATE_SEMI_COLON TOKEN_SEMI_COLON)
(set-state-type STATE_DOT TOKEN_DOT)
(set-state-type STATE_COMMA TOKEN_COMMA)
(set-state-type STATE_ID TOKEN_ID)
(set-state-type STATE_NUM TOKEN_NUM)
